apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
    # The following enables Cloud Tracing
      tracing:
        stackdriver: {}
    # The following enables DNS Proxying
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
kind: ConfigMap
metadata:
  name: istio-asm-managed
  namespace: istio-system

