apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-int-ext
spec:
  hosts:
  - httpbin.virt.local
  http:
  - route:
    - destination:
        host: httpbin.org
        port:
          number: 80
      weight: 50
    - destination:
        host: httpbin.meshed.svc.cluster.local
        port:
          number: 80
      weight: 50
